### ISSUE TITLE
Please keep the C# extension version synchronized with the latest official release from Microsoft.

### ISSUE THREAD

**Issue by zhouxinghong** [muhammadsammy/free-vscode-csharp#79]
## Describe the solution you would like

Hello everyone! 😃
Please keep your C# extension version in sync with the [latest official Microsoft release.](https://github.com/dotnet/vscode-csharp/tree/v2.46.32)

**Comment by zhouxinghong** [comment]
Thank you very much for porting the latest official Microsoft C# extension to the Theia platform. 👍🍦😎

**Comment by Blinc88** [comment]
https://share.newsbreak.com/8w003n20

**Comment by muhammadsammy** [comment]
Thank you!
The latest version on now has the latest changes from upstream.
